import { constant } from '../../../utils/constant'

export const formStepOptions = [
  { value: 1, title: 'Step 1 (Initiated)' },
  { value: 2, title: 'Step 2 (Details)' },
  { value: 3, title: 'Step 3 (Ameneties)' },
  { value: 4, title: 'Step 4 (Images)' },
  { value: 5, title: 'Step 5 (Completed)' },
]

export const mailTypes = [
  { id: 1, title: 'Porperty Approved' },
  { id: 2, title: 'Porperty Rejected' },
  { id: 3, title: 'Porperty Pending' },
  { id: 4, title: 'Porperty Notification' },
]

export const propertyStatus = [
  { id: 1, title: constant.PROPERTY_STATUS.PENDING },
  { id: 2, title: constant.PROPERTY_STATUS.APPROVED },
  { id: 3, title: constant.PROPERTY_STATUS.REJECTED },
  { id: 4, title: constant.PROPERTY_STATUS.DELISTED },
  { id: 5, title: constant.PROPERTY_STATUS.SOLD_OUT },
  { id: 5, title: constant.PROPERTY_STATUS.RENT_OUT },
]

export let initialPropertyDetailsValues = {
  user : '',
  images: '',  
  property_title: '',
  company_name: '',
  description: '',
  short_description: '',
  latitude: '',
  longitude: '',
  land_area: '',
  land_area_unit: '',
  is_maintenance: '',
  property_variety_type: '',
  property_availibility_type: '',
  builtup_area: '',
  builtup_area_unit: '',
  rent_amount: '',
  deposite_amount: '',
  property_type: '',
  bed_rooms: '',
  washrooms: '',
  floor_number: '',
  total_floors: '',
  property_floors: '',
  balcony: '',
  is_wings: '',
  unit_number: '',
  total_wing: '',
  wing_name: '',
  property_variety: '',
  property_rent_buy: '',
  rent_is_nogotiable: '',
  deposite_is_negotiable: '',
  availability_date: '',
  availability_duration: '',
  property_age: '',
  furnishing_status: '',
  parking: '',
  water_supply: '',
  washroom_type: '',
  granted_security: '',
  other_amenities: '',
  door_facing: '',
  preferred_tenent: '',
  pet_allowed: '',
  non_veg_allowed: '',
  expected_amount: '',
  drink_allowed: '',
  smoke_allowed: '',
  pg_rules: '',
  exected_amount_sqft: '',
  per_sqft_amount: '',
  monthly_maintenance: '',
  ownership_type: '',
  dimension_length: '',
  dimension_width: '',
  width_facing_road: '',
  sewage_connection: '',
  electricity_connection: '',
  rera_number: '',
  is_rera_number: '',
  property_current_status: '',
  possession_status: '',
  possession_date: '',
  total_towers: '',
  total_units: '',
  project_area: '',
  project_area_unit: '',
  unique_view_count: '',
  ip_address: '',
  user_agent: '',
  host_name: '',
  status: '',
  status_text: '',
  is_deleted: '',
  added_by: '',
  updated_by: '',
  publish_date: '',
  created_at: '',
  updated_at: '',
}
