
export let initialBlogValues = { 
    title: '',
    description: '',
    short_description: '',
    author_name: '',
    cat_id : '',
    tags : '',
    meta_title: '',
    meta_description: '',
    meta_keyword: '',
    comment_enabled: '',
    canonical_url: '',
    banner_image: '',
    banner_size : '',
    banner_type : '',
    banner_video : '',
    youtube_url: '',
    publish_date  :'',
}
