
export const initialSubscriptionValues = {
    plan_title: "",
    property_category : "",
    user_type: "",
    plan_names: "",
    duration_days: '',
    leads_counts: '',
    contact_whatsapp_notification: "", 
    promotion_on_web: "",
    promotion_on_meta: "",
    paid_promotion_on_sqft: "",
    paid_video_promotion: "",
    ind_sponsored_ads: "",
    agreement: "",
    assign_rm: "",
    plan_amount: '',
    plan_discounted_amount : '',
    plan_gst_per : '',
}